sudo: required
services:
- docker
language: node_js
node_js:
- 8
cache:
  yarn: true
  directories:
  - node_modules
stages:
  - lint
  - test
  - security
  - name: docker
    if: branch = master
  - name: deploy
    if: branch = master
jobs:
  include:
  - stage: Lint
    script: npm run lint:js
  - script: npm run lint:text
  - stage: Test
    script: npm test -- --coverage
    after_script: cat coverage/lcov.info | node_modules/.bin/coveralls
  - stage: security
    script: docker run --rm -v $PWD:/target stono/hawkeye
