sudo: required
services:
- docker
language: node_js
node_js:
- 8
cache:
  yarn: true
  directories:
  - node_modules
stages:
- lint
- test
- security
- name: docker
  if: branch = master
jobs:
  include:
  - stage: Lint
    script: npm run lint:js
  - script: npm run lint:text
  - stage: Test
    script: npm test -- --coverage
    after_script: cat coverage/lcov.info | node_modules/.bin/coveralls
  - stage: security
    script: docker run --rm -v $PWD:/target stono/hawkeye
  - stage: Docker
    script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $DOCKER_REGISTRY
    - docker build . --tag $DOCKER_REGISTRY/$REPO --build-arg SITE_URL=$SITE_URL
    - docker push $DOCKER_REGISTRY/$REPO
env:
  global:
  - secure: iV+70zGlALP+h+VYy/ZOaN25UJM7jNloxoJjQXnH9JZYvwXtyninH4grS8cSHkBU/oqtlNoADRvlqvI4Zw8YxdEtLVA4FdOROSU6AwVIOOQlWfI/saHAfCdy6SF6Y02sMEpBu15cmELBn4Np/2bQUrgZIFv1RCJ3q+hxlWmjOsTrsg4QZ2AZub7m2X2I5pjU8yNDYXIWPQV4f2fd0zvvm3xcuEXS0goNOKte4GqP2YjUTXck1sS0bM0H07BAhUftiqTSSRAocNoFOalPPcBKn7g4KIdrk/071mr1mspQlTSbxJdKHr/0/YeaBlZOewY7x42Jru9MweaAcfiZgZzdjBaZJPNOBDrbSXa8Wbo0ep/Phax2y38kDiu6AvWIra5xnRyk7rqwYnmwtjdRcxoA/smXzqW70VOht7jQslUdS99d1Jr3N4xtA2R3k4fW2JzpB0A98vQiohJ1aA3jMw0IfxgUu934ShrziuzGxnUvXvJWMsHRKjo+KMfOJb7okkBshBfO4SHrY7kJAhc79aTaDntKBqX27fPlF8zLzG8NUQkpjlU5Hgl2KWsxmYBJ5sOGQsgMfLNpKxq0wlpnTMueKFqsvfe0rAcA01biK256MBaLs/Y/4JFuonlopcraoSP8p2UFwfSz7vUur9lnwfVFe/c3stdIVrJnope5ZE/bX0U=
  - secure: fzplWeBJCZL/wPPBJMY0xUavD4e3Vymk8guRWSGoZOoEqOnHP7vAvdeq70Z8GCHEfGTFp0OFdxERFq+DYBrtSdd+cPqFSDGioqvFrz3tqi+o2IDeBJIbqvi9G8PrvNYiRVse5pYfYtNSLGSd2dzV/viCpV6THSFC+HfKE4j3U60Z6BIbIPb52H8XRSHxysjvQW07dbreoPMiajxAdDtQ6uCnsixN3SxVhrWKn/AwBOawebhuxPNqQp2nu0P2T5oQylL1auoUMgwmEKzJaPWLq0LZtureOylybgB99K1ScQeS/mfbk/2zmS4mtvioQUOAyR7JYu83UZF6f4aV2IZNDhmpDP7puR1H4ScakXJ+aN+Gd6PB56hXln5mAA53aVsNzErmUufGTh3S/CaecpexaFi2HQb5ZLhJ7ciLDcty7SZNW8aRF7owgBONiHL2lC2dQ3sgxewATj3XI+B25l1/wgFG6cjRDt4hE5+dNhlHS8f+FZGkmv+ZxQCIiY31WNMCvg9W3VvH6n0Vb3gPUqRS0Jelw6KhqCZmh45pTblAiDHOjdCuZoA85cM7HwW6FlfyBtxFfRW25neh9ZJB29B1IXd+JNQk5JBFycJ0nGmDT5SIYVKimv70QX5Q4HQ85dtnY+unzn47VRcYapmFv27neAUfYgAGdEdpADxZ8z6wq1Q=
  - secure: odf8woDh71Tiyza+eFZvbzu5qUKC+C+jY7HFVdfVMUyNZxgs91V3tdF54HAWnbpWzu9QLgmCGuCuH90t0LJiNbTjeKPYLorpAhH39Xi8lIA2QLZXr+P9CbN9XDJkjFZQi+iBybzqt3dpdSA8ma7TVQctlVVvoW1MHDO7XRxNZ7DNfVVEZW7vJ4dyBoe/5HscDv4o0sqE1ZXrauIQMGvj9on54vgL4FRjtGOR1QIrj+kDQq7lsjGC/j+sPYVK8QM88KNoams7sOSeiUrxxrz+gWu/TMK8zThNDLfjgADcu1dP/LgKnLkw1AknVR/aSVq8o5r8CD3V3bIv1KuaSOINIqBxfkh3hnAuV235ybR2Bebq3aMFcJtmWrbzyTkFCb3Ixa0/eJtUGrFnmKCz48zyLZb7eG+eVeZjA3lpcVoES90pawrxQ+2z3koZHZ+Cbgud58nLie5OW8yCnDDwEHaOIkgsjJjuhdoMbWEyccqz7JJOmfYF1p/yIFyP4awlA2d+Q4U/OLPRwcQx8r7TLxlg68cOfQGNzHkOxzN9C1zqfJ1lJ8y+a9LxGXQWmgnV3wnYfEg9vXkZ94dmA9/ZaOsMis94a9NVHf6CMOXpoAqTg6AeXvooyYsglBWgrA9+X6z9tGRJ1R170xqfiSh4yemkKRkUwwtj+kIFFiUvrWU61Ik=
  - secure: agmDqo33LsNKJOAPaM55xSKW8AZLk01aEZ2wGW4sxeUtxNoagQooqAG1RtvDRG+6HqKlEHxO6rsOj+zTp1kxtzXKDXzCuq8PO1uwBozbFiO/Udj+tEAnHvrxuB1xOBbrvB+i8hSG9YRHr6zdxSsI1PHmV+jFOtWc70J2887jjcHULByNoXFvJoR6aJZUASKI7cvIuuP6Y39DC7QGwjqnCN7bf9KjKI81TqVw6ZKxWmyNg4sSFB+dwEavm7idqeBfZKbIH/yP2W0+DAIIVAZFIwEmOsu1fck5A4bwWoUD//KELjI8cPs48X9C+vXqsgFwTmrNTbEwuTIOAOMCO8tCDJvG2kyGWF5TzUDFYktr+ZjIW1tY7peCfdnz01cq8sF4My/c5kM0Yw/oVGX7f0YoJ8c91F3Pfn70i1vLOZ3atzPDFzP0BB9oF/hL3zd6BHg4voEZx+XV/ZKNijfyZGpruBQ6w0AspihgAoLjskD/5LDfjfV12AQfNhnWAwMY9YUSolllXaHpZtgWD5KGcLr579Pgh3l55fzTVvUbQwRRYQQs+uyaoxFuSOeUIyUEtLksjPgxXR3wmh3FJQCC2gBxhQYLUwFMieI0w0aPCvf2Ck95hN1Z092XD5aAvRI/iWFF1VzyCZUV6+LStgl8n/uzNaa4/Y/osMr/mh7BHkKsaeQ=
  - secure: uz+M2J/WNKN/52Z3YXlXo128/C0l9P2ApwHyIiJfARw38a7izX3fD4WTEA9fM2oSMLpCmc4aWXkINr/cfZSPV10W/zu1nKkOG+jEKn5E0gN38lzGX6uzUFfWpidT/bQPFmkWruc6DkIm63vVPRzYkQnTQMs6m+C1azMAlmtxGWaFPumrsAAQX1gFMQe3jPZY6bAZlq9n4ZGRHcG4iFIh8jK6yTmsdqGHidiwdKNgHzx8s3Vv8hlM05rAYhmvsJ1MnSqJSEhQ7tiaGNVX+f+nFTJ6oWd5vA9wkkhm0GZ7iBMpbo5DnNJTRZWLkTn1ZfSuUPXWZi7NPqlIdm+DlqoerBRm/+ED7NCiITWKqPSpcM7GqRxj5TBiLt/z23TiqlGONZdR/0kbPBVMH2Hgub343eqNgHNdJWstcZKb11uYazMswmLi/3A9p7jYf2I6rbUqjLlozOxaHDUNOtSlZUHYkyzH8OfUoRoZ4b1kxAlkCHaNGGth3GkQfaKXNnzk8oTu4jGXiSsCoTs5XM8efPK1Ng+jDFbIBo1qhT9y18E8Ov10S5zvpx3327+8t2O33OeW9lWwyo7L4WcuWBtQRQHf2e3v3aHx8/I1YRy/QYoxikUXWdxrqvGt+uGYztAGfAlLsgUZI8Tans8TimdSCyEbcgPBE4AYzdWEWDaplvrxaMo=
