sudo: required
services:
- docker
language: node_js
node_js:
- 8
cache:
  yarn: true
  directories:
  - node_modules
stages:
  - lint
  - test
  - security
  - name: docker
    if: branch = master
jobs:
  include:
  - stage: Lint
    script: npm run lint:js
  - script: npm run lint:text
  - stage: Test
    script: npm test -- --coverage
    after_script: cat coverage/lcov.info | node_modules/.bin/coveralls
  - stage: security
    script: docker run --rm -v $PWD:/target stono/hawkeye
  - stage: Docker
    script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $DOCKER_REGISTRY
    - docker build . --tag $DOCKER_REGISTRY/$REPO --build-arg SITE_URL=$SITE_URL
    - docker push $DOCKER_REGISTRY/$REPO
env:
  global:
  - secure: T/nG3kEQHgmX2kIAacJNeWwbbfNGUkMrvMNLwPsRA1qPVNBIC4VUntZcRlAp2p/lX/JkOm21Xo0eMErqYX2MgiBj+2lm1h/If4T5YSAko1xYUVAM3KnhC8OiTpzy0/mrtuvXVefyNBFHEiZjpq2qwhEFrVrLLTH+wn4BvirCDEnSzdHqc+sS3eleKjAaXKPXrqIuKFhQLpp50B9ADrJ48tB80Zq2st5zb2zrgkswlIj2N2RGUfFOt/zUTpHZ3KJvs78P73qQLzoSM0OGs3hOmQzn0ByLCijwg7RtTXz6MAH2Reniz4XmZN/NzYlaUmCUmTR6PrXMCkWthn9wa0goRAeiExFyRQhwe57ZXdz99yaEpqrel7brOh25b9AxwwNlGfiF5kHDGJadiyPKfzrrOO5J3POUwJQLIMCS1nnDeFmDS9RexQbysD/hd64xaSt3WR6F3dOMhez1qBzuORhpfwk4/SQH/g7n0JNgt6/f1McIvHj4I/9sSWgvmBqluhC4X/rxmj2wIqSDnyaNYS+Aa2k2bpAnT7xbXdq+iJCR2cpv9O8jP+bqWipx8gYaQMw3yYG5xTtitBOlUlkdpJNJYa+Xm+ICa/g3CP96l1ZLKA5akKmqkeelY9sVKJHaaZnbAjRvk2i3ZjLFfBcgTPVaSmSjTEOwKttImxcDMb2koRw=
  - secure: AcZE2dU8fqYFxadvxGPA37Vdmrtm6BRwjxzc0WjbbLiVlZIKN+3mJCoOTk7EcoDXy6gBbVdN6Ec71YEir3zFKDNbSTydhPCiDzmMPoU0Ym6vChYlbTfxXhIYgQ4D/oLxr5e2RqLZ/hF+HkIK1IB3gy9fEthCBwDDQHS3mVDHA+Gu3jj3o0tRa44tnwnnJNBeEx82N17VfMTLO/V344hg5pQ3dmN2LiYUMRnmXwR8/PtYm7muWkc2pqxexRUPP8VezKH0x8+25nAOXYlgHccOE4vhxnNn5EXa3zqRM0rw3+o75qslWYtp+zzRKu9vyRzjKs7XJbot+Ni/Tz3swD0WqTtV47I0iiUCFr9z4UWVr5z0B9XqmLxk309W/tw1mOpwiv2TP0CBjdiadxl9rYng5rKOvQx55eClfjcYm6E7JDb9QrLlw6LgFaDd8wfqnxV7v4/Vm/dF6iNl43IRIHp2OWK3vrCw6s1Vat6fpzKFclhdCsepL38bABUQtewv2nBEuixjeHg6rnQhVQU6cFNNSOX9Ib7U2BRC0SiPyEud/NLVCRYYDMN6N28mE4p1Xnzp1L53ODc0YEf3jcN1xHc/urn28QZJMZx9Dlr0NZyB91IvcOvU/amIdOn2Q/HDHcrHwE6b7dQn9ZCnHjSP/3x/n2WxSTpetrHxDCXYshe5ZsU=
  - secure: Fox3KyTRp9zLJbvzaiAynNEeNVz8bzZhm1zvwSVvVSdcU7usaXWvCH2gdk3wUY/PkwHhn6lB7kPZL0TBWkMD+EqEImIY7xw75eg67rQ8NT7DEn4J3mcvXnPkxrfbACB9/h6YMwIkHljhIMS0Fia92dC6f2O8T9jr5D3EZOB3lA3tJF/uuYpC+QTdifVonw9DhPRatmf/ix2GtnKb9GVD6tT50TrPrjd1KwGn2I/GMphJLoqHOb4yjskDI2DfCq7I3idBlHZcuV1Caq9xwKB1ypPgIKL9MNmWi6/I1vHUTdJgKeVFBN7sy119kYbey5b0mvstzdR1JYsfMd/2TphOP8BTcPOaEPuLDTG9QEqUTBle4Y3A9RTdqA1iEbCQB6qw7yZy2rpsbPXZDK1/W+5RPwggZWe7gGPCy53gNsColLMEh9fg9H2f27CDD8mOk2tDnoFUaBPEvUIUPeFrKL3SUYa1EIE1sMOm6VTZEqucq4rC8eu8kWSBcCz/va+u7RY7MgS1jjxdo3cNNTfa46Qc60X0LDyxU5gnggr5jagjFy2G/wYcxGLQ3ndVJ5WmybiZn6FQ6OpCL1Cr/jWTyyW0hiQCUPa1h15dGhAFTIzwN+Pmrtw6Iw+2WK/zoj5U/4fBSy/TW3gv1XiwMDhBS1AzaBMjfJmYkoDZxemPEoezyD8=
  - secure: RdnG1fMLPgK7Gf21Z5d+YMSTl8R2CFedWC1yMnGXNbMf0aymAGHfXqcjN1xQHbzjGymRSZhDqK3jPgXnY2sT8CAtJrdEQ1RLsKZJ2hmiiTrnoJoEBhpbuFwL/wyNfl1tVa42iLNJjnfIktA0+Pw8gfkWq8kqBHe2qaa2XrHP5FyV7/Vz6a3tTbe+MSDfhcMLFL8psjlGSQLnvtF4BQUYoSDfxdg0BxGGBidOb7i+y+Ymw1yAd3fX/3dgOi8r05aDXM7sfKNjvG5DhwSI/AgZCnO9zL5vKUyINchywxhup94SVZyRI+ff/+tB6o9ps/0zz/5oxgcRnZ2q0sJ5x9KXoK4iFH1K+/zeEObpbRg6r2aevZbArBoom83z82kp5C/UcARn9KyBa2igH7IklsTvv4y/Atw+EZBpK35Zz96Z5+92vZR7JcT5jyhFc1cI+9/p9w6Ti/yu4INViy94eJ+K8gK0BiTF+YIcMnQp9MKbRk+x/5MmSAf854djg5wrA6Z+vo2IIy2u3no6rYIj0HPwCMsjbn/Rbo7L+u5/LSc9s2I7lUDWVhxXtyedwMD47jESIT1qcvP9J+QoeqYx9pI6yBwsWc44Hqe1rvmn0DTV204r5V7fToNlVfhCyhPuU5nuu4tQaUWJFrl2Jk6lYg/G9Kenc0lTksPFj8LfIUsrm08=
  - secure: EW23CkIKI0XlSx4XThhn+80r2hCh1+DOdYVD6Qtqi5b/7tEQ+JqVNH+wENcco2IubTkETBHx0bfWzi7QelXX70ccwKRrZSxoi+DesyBIMsvx24khIZyWmbrAmEKYUP2bf5+dw3/I+f/gd7UTy+NuMC4WONK0140rZWytLcQPIOV30MOt9Q5/tDoIPmvj2BnhetSU9YaHgBcqT3DlFEVxe2PY8i1htvTjLHtvGqqzTZGZU+JusOcWYqdSS0SC7ixp+2VHrI5DJ6IIUOQ7/8jE/WCQpA2MArm5815mveTBzqMVLFOy4sKHzwggxD6GRl1I3d52QEUL0qbXpK/SwLKTtzsLf1OILO88caEuPbPInKRx//JfFg/65zJ/G8Of9F26sMQ9RVU8c6/dU6bQMeSWnrKYHomoyvGJs/RxtohvPuj5SSKooD5BcqKRNodZ47BK0lyXD+HSat76XG243saOp2ISzyV+CIQB4A89qYoXHPpIWba5uJzuIbhTSQtEXyVTVQmryFtVNKc1GS2SwKPLHaAYf2VC0dY/trK1l1gxfhTrzQiv/E5i4rFkfzUB72V5CSOFHC3MxOeAvnof2NXR4mJAOuLtSSADOheN3fnFL2Dlg5ZE3Hl8srgx7HcLdSc7P0+KdfFG1Key33Fx7SriZ89/+1zD24Hma8NfbGVdEjQ=
