version: 2
jobs:
  build:
    working_directory: ~/app

    docker:
      - image: cimg/node:16.13.2
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD

    steps:
      - checkout
      - restore_cache:
          key: npm-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: npm-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: ./go linter-js
      - run: ./go linter-css
      - run: yarn test --coverage --runInBand
      - run:
          name: Upload coverage results
          command: |
            cat coverage/lcov.info | node_modules/.bin/coveralls
          when: always
      - run:
          name: Build and package
          command: |
            GATSBY_CPU_COUNT=2 SITE_URL=$SITE_URL yarn run build
            find public -regextype posix-basic -regex '.*\.\(js\|css\)\(.map\)\?$' -print0 | xargs --null -I@ sh -c "gzip -c @ > @.gz"
      - persist_to_workspace:
          root: public
          paths:
            - '*'

  deploy:
    docker:
      - image: cimg/node:16.13.2
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD

    steps:
      - add_ssh_keys:
      - attach_workspace:
          at: public
      - run: tar -czf homepage2.tgz public
      - run: scp -o StrictHostKeyChecking=no homepage2.tgz $DEPLOY_USER@$DEPLOY_HOST:/tmp
      - run: ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "cd /tmp && tar -xf homepage2.tgz && chown -R $DEPLOY_USER:$DEPLOY_USER public && mv public homepage2-${CIRCLE_BUILD_NUM} && rm homepage2.tgz"
      - run: ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "${DEPLOY_PATH}/bin/promote /tmp/homepage2-${CIRCLE_BUILD_NUM} /srv/main"

  security:
    docker:
      - image: owasp/zap2docker-weekly
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD

    steps:
      - run: zap-baseline.py -t $SITE_URL -u $ZAP_CONF_URL

  post-deploy:
    docker:
      - image: cypress/browsers:node16.5.0-chrome94-ff93
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD

    steps:
      - checkout
      - restore_cache:
          key: npm-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: npm-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: ./go test-e2e --record
      - run: ./go lighthouse

      - store_artifacts:
          path: reports

workflows:
  version: 2
  pipeline:
    jobs:
      - build:
          context:
            - docker-context
      - deploy:
          context:
            - docker-context
          filters:
            branches:
              only: master
          requires:
            - build
      - security:
          context:
            - docker-context
          requires:
            - deploy
      - post-deploy:
          context:
            - docker-context
          requires:
            - deploy
