version: 2.1
executors:
  node-executor:
    working_directory: ~/app
    docker:
      - image: circleci/node:11.13

jobs:
  build:
    executor: node-executor

    steps:
      - checkout
      - run: yarn
      - run: ./go linter-js
      - run: ./go linter-css
      - run: ./go linter-text
      - run: yarn test --coverage --runInBand
      - run:
          name: Upload coverage results
          command: |
            cat coverage/lcov.info | node_modules/.bin/coveralls
          when: always
      - run: bin/audit
      - run:
          name: Build and package
          command: |
            SITE_URL=$SITE_URL TRACKING_ID=$TRACKING_ID yarn run build
            find public -regextype posix-basic -regex '.*\.\(js\|css\)\(.map\)\?$' -print0 | xargs --null -I@ sh -c "gzip -c @ > @.gz"

      - persist_to_workspace:
          root: public
          paths:
            - "*"

  deploy:
    executor: node-executor

    steps:
      - add_ssh_keys:
      - attach_workspace:
          at: public
      - run: scp -o StrictHostKeyChecking=no -r public $DEPLOY_USER@$DEPLOY_HOST:/tmp/homepage2-${CIRCLE_BUILD_NUM}
      - run: ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "sh ${DEPLOY_PATH}/bin/promote /tmp/homepage2-${CIRCLE_BUILD_NUM} /srv/main"

  e2e:
    docker:
      - image: cypress/browsers:node11.13.0-chrome73

    steps:
      - checkout
      - run: yarn
      - run: ./go test-e2e --record

workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build
      - e2e:
          requires:
            - deploy
