export default [
  ['Ruby', 'ruby'],
  ['Rails', 'rails'],
  ['JavaScript', 'javascript'],
  ['TypeScript', 'typescript'],
  ['React', 'react'],
  ['SQL', 'mysql'],
  ['Docker', 'docker'],
  ['HTML', 'html5'],
  ['CSS', 'css3'],
  ['Python', 'python'],
  ['Java', 'java'],
  ['AWS', 'amazonwebservices'],
  ['Kubernetes', 'kubernetes'],
]
